export const L = {
  "status":"success",
  "data":
    [
      {
        "id":"ChIJxR2dbizN1EARTPqfqSHZ1RE",
        "provider":"google_places",
        "addressLine1":"Lavina Mall",
        "addressLine2":"Vulytsya Berkovetsʹka, Kyiv, Ukraine"
      },
      {"id":"EiFMaXV0ZXJhbnNrYSBTdHJlZXQsIEt5aXYsIFVrcmFpbmUiLiosChQKEgnHDH1VVM7UQBFXacMqn0psNxIUChIJBUVa4U7P1EAR_kYBF9IxSXY","provider":"google_places","addressLine1":"Liuteranska Street","addressLine2":"Kyiv, Ukraine"},
      {"id":"Eh9MJ3ZpdnMna2EgU3F1YXJlLCBLeWl2LCBVa3JhaW5lIi4qLAoUChIJA6djl13O1EARK1RWZL519FsSFAoSCQVFWuFOz9RAEf5GARfSMUl2","provider":"google_places","addressLine1":"L'vivs'ka Square","addressLine2":"Kyiv, Ukraine"},
      {"id":"ChIJYUAVHhRXIkcRX-no9nruKFU","provider":"google_places","addressLine1":"Lublin","addressLine2":"Poland"},
      {"id":"ChIJsYW_01HO1EARuCHrjsb86-k","provider":"google_places","addressLine1":"Louis Vuitton","addressLine2":"Khreschatyk Street, Kyiv, Ukraine"}
    ]
};
export const Lo = {"status":"success","data":[{"id":"ChIJsYW_01HO1EARuCHrjsb86-k","provider":"google_places","addressLine1":"Louis Vuitton","addressLine2":"Khreschatyk Street, Kyiv, Ukraine"},{"id":"ChIJr1ZFdSTLG0cRrNshm2OufMs","provider":"google_places","addressLine1":"Łódź","addressLine2":"Poland"},{"id":"ChIJNb4CTP_O1EAR8IIasChOAOY","provider":"google_places","addressLine1":"LoggerHead","addressLine2":"Tarasa Shevchenko Boulevard, Kyiv, Ukraine"},{"id":"ChIJcQi2q_jO1EAR8j88rq6ISN4","provider":"google_places","addressLine1":"LOFT Game Space","addressLine2":"Khreschatyk Street, Kyiv, Ukraine"},{"id":"ChIJgy6CYP_O1EARqW_p1TStv4g","provider":"google_places","addressLine1":"Loft Bar","addressLine2":"Bessarabs'ka Square, Kyiv, Ukraine"}]};
export const Lon = {"status":"success","data":[{"id":"ChIJVz5E2GrO1EART34YLwGkegQ","provider":"google_places","addressLine1":"LONDON COFFEE","addressLine2":"Verkhnii Val Street, Kyiv, Ukraine"},{"id":"ChIJdd4hrwug2EcRmSrV3Vo6llI","provider":"google_places","addressLine1":"London","addressLine2":"UK"},{"id":"ChIJRYHfiwkB6DsRWIbipWBKa2k","provider":"google_places","addressLine1":"Lonavala","addressLine2":"Maharashtra, India"},{"id":"ChIJC5uNqA7yLogRlWsFmmnXxyg","provider":"google_places","addressLine1":"London","addressLine2":"ON, Canada"},{"id":"ChIJI5ZxqmvO1EAR5aCH1K0qL1E","provider":"google_places","addressLine1":"LONDON","addressLine2":"Verkhnii Val Street, Kyiv, Ukraine"}]};
export const Lond = {"status":"success","data":[{"id":"ChIJVz5E2GrO1EART34YLwGkegQ","provider":"google_places","addressLine1":"LONDON COFFEE","addressLine2":"Verkhnii Val Street, Kyiv, Ukraine"},{"id":"ChIJdd4hrwug2EcRmSrV3Vo6llI","provider":"google_places","addressLine1":"London","addressLine2":"UK"},{"id":"ChIJC5uNqA7yLogRlWsFmmnXxyg","provider":"google_places","addressLine1":"London","addressLine2":"ON, Canada"},{"id":"ChIJI5ZxqmvO1EAR5aCH1K0qL1E","provider":"google_places","addressLine1":"LONDON","addressLine2":"Verkhnii Val Street, Kyiv, Ukraine"},{"id":"ChIJbVivV1pD65QRcfkUxqURrCM","provider":"google_places","addressLine1":"Londrina","addressLine2":"State of Paraná, Brazil"}]};
export const Londo = {"status":"success","data":[{"id":"ChIJVz5E2GrO1EART34YLwGkegQ","provider":"google_places","addressLine1":"LONDON COFFEE","addressLine2":"Verkhnii Val Street, Kyiv, Ukraine"},{"id":"ChIJdd4hrwug2EcRmSrV3Vo6llI","provider":"google_places","addressLine1":"London","addressLine2":"UK"},{"id":"ChIJC5uNqA7yLogRlWsFmmnXxyg","provider":"google_places","addressLine1":"London","addressLine2":"ON, Canada"},{"id":"ChIJI5ZxqmvO1EAR5aCH1K0qL1E","provider":"google_places","addressLine1":"LONDON","addressLine2":"Verkhnii Val Street, Kyiv, Ukraine"},{"id":"ChIJc5mIA0TP1EARzfo1REUO58o","provider":"google_places","addressLine1":"LONDON COFFEE","addressLine2":"Velyka Vasylkivska Street, Kyiv, Ukraine"}]};
export const London = {"status":"success","data":[{"id":"ChIJVz5E2GrO1EART34YLwGkegQ","provider":"google_places","addressLine1":"LONDON COFFEE","addressLine2":"Verkhnii Val Street, Kyiv, Ukraine"},{"id":"ChIJdd4hrwug2EcRmSrV3Vo6llI","provider":"google_places","addressLine1":"London","addressLine2":"UK"},{"id":"ChIJC5uNqA7yLogRlWsFmmnXxyg","provider":"google_places","addressLine1":"London","addressLine2":"ON, Canada"},{"id":"ChIJI5ZxqmvO1EAR5aCH1K0qL1E","provider":"google_places","addressLine1":"LONDON","addressLine2":"Verkhnii Val Street, Kyiv, Ukraine"},{"id":"ChIJc5mIA0TP1EARzfo1REUO58o","provider":"google_places","addressLine1":"LONDON COFFEE","addressLine2":"Velyka Vasylkivska Street, Kyiv, Ukraine"}]};
